app:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 500Mi
opensearch:
  envs:
    OPENSEARCH_JAVA_OPTS: ' -Xms500m -Xmx500m '
  resources:
    limits:
      cpu: 1000m
      memory: 1.5Gi
    requests:
      cpu: 500m
      memory: 1Gi