name: Deploy

on:
  push:
    branches:
      - "main"
      - "production"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  deploy:

    if: github.repository == 'quarkusio/search.quarkus.io'

    runs-on: ubuntu-latest

    env:
      QUARKUS_PROFILE: ${{ github.ref == 'refs/heads/production' && 'prod' || 'staging' }}
      TAG: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Helm
      uses: azure/setup-helm@v4.0.0
      with:
         version: 'v3.13.3'

    - name: Log in to OpenShift (Dev)
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE_DEV }}

    - name: Log in to OpenShift (Prod)
      if: ${{ github.ref == 'refs/heads/production' }}
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN_PROD }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE_PROD }}

    - name: Create ImageStreams
      run: |
        oc create imagestream search-quarkus-io || true
        oc create imagestream opensearch-custom || true
        # https://docs.openshift.com/container-platform/4.14/openshift_images/using-imagestreams-with-kube-resources.html
        oc set image-lookup search-quarkus-io
        oc set image-lookup opensearch-custom

    - name: Log in to OpenShift container registry
      run: docker login -u "$(oc whoami)" -p "$(oc whoami --show-token)" "$(oc registry info)"

    - name: Build container images and Helm charts, push app container image
      run: |
        ./mvnw clean package \
          -Drevision="$TAG" \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry="$(oc registry info)" \
          -Dquarkus.container-image.group="$(oc project --short)"

    - name: Push OpenSearch container image
      run: |
        docker push "opensearch-custom:latest" "$(oc registry info)/$(oc project --short)/opensearch-custom:latest"

    - name: Deploy Helm charts
      run: |
        helm upgrade --install search-quarkus-io ./target/helm/openshift/search-quarkus-io \
          -f ./src/main/helm/values.$QUARKUS_PROFILE.yaml